spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: vinhos
          uri: lb://VINHO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/vinho/**

        - id: vinicolas
          uri: lb://VINICOLA-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/vinicola/**

        - id: pedidos
          uri: lb://PEDIDO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/pedido/**

        - id: imposto
          uri: lb://IMPOSTO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/imposto/**

        - id: notafiscal
          uri: lb://NOTAFISCAL-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/notafiscal/**

server:
  port: 9999
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: vinho-service
        url: /vinho/v3/api-docs
      - name: vinicola-service
        url: /vinicola/v3/api-docs
      - name: pedido-service
        url: /pedido/v3/api-docs
      - name: imposto-service
        url: /imposto/v3/api-docs
      - name: notafiscal-service
        url: /notafiscal/v3/api-docs